size_multipliers:
  Small: 0.7
  Medium: 1
  Large: 1.3
pizzas:
  Margherita: 5
  Salami: 6
  Tonno: 8
ingredients:
  Onions: 1
  Cheese: 2
  Olives: 2.5
promotions:
  2FOR1:
    target: Salami
    target_size: Small
    from: 2
    to: 1
discounts:
  SAVE5:
    deduction_in_percent: 5